---
- name: Install Vector | Get Vector distrib
  ansible.builtin.copy:
    src: templates/0.47.0-1_amd64.deb
    dest: "/tmp/vector-0.47.0-1_amd64.deb"
    mode: "0644"

- name: Install Vector | DEB install
  become: true
  ansible.builtin.apt:
    deb: "/tmp/vector-0.47.0-1_amd64.deb"
    state: present
  notify: restart vector service
