---
driver:
  name: docker
lint:
  ansible-lint .
  yamllint .
platforms:
  - name: instanse
    image: aragast/netology:latest
    pre_build_image: true
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
  - name: oraclelinux
    image: oraclelinux:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
